name: Deploy

#when should the jobs run, when code is merged(pushed) and when code is pulled(pr)
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    #which particular machine(server) is github using my default

    steps:
      - uses: actions/checkout@v4 #by default the branch will be main and this tells github to checkout from this branch to the current branch
      - run: docker build . -t ranjinivasista/next-js-app #building docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker push ranjinivasista/next-js-app:latest
