name: Integration

#when should the jobs run, when code is merged(pushed) and when code is pulled(pr)
on:
  push:
    branches: [ "main" ]
  pull_request:  
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest 
    #which particular machine(server) is github using my default

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4   #by default the branch will be main and this tells github to checkout from this branch to the current branch
    - name: Use Node.js ${{ matrix.node-version }} #optional
      uses: actions/setup-node@v4  #telling github to set up environment(node in this case)
      with:    #run with all node versions given under strategy
        node-version: ${{ matrix.node-version }} 
        cache: 'npm'  #package manager
    - name: "Installing dependencies"
      run: npm i #download all necessary dependencies
    - name: "Build command"
      run: npm run build #build job is done

  unit-tests:

    runs-on: ubuntu-latest 
    #which particular machine(server) is github using my default

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4   #by default the branch will be main and this tells github to checkout from this branch to the current branch
    - name: Use Node.js ${{ matrix.node-version }} #optional
      uses: actions/setup-node@v4  #telling github to set up environment(node in this case)
      with:    #run with all node versions given under strategy
        node-version: ${{ matrix.node-version }} 
        cache: 'npm'  #package manager
    - name: "Installing dependencies"
      run: npm i #download all necessary dependencies
    - name: "Running test cases"
      run: npm test #run tests

